#!/bin/bash

# set -x

. .bashrc

cd $HA

function get_dev() {
     cd /workspaces/versatile_thermostat/custom_components/versatile_thermostat/
     pip install pytest
     pip install -r requirements_dev.txt
     pip install -r requirements_test.txt
     sudo chown -R vscode:  /home/vscode/core
     cd -
}

echo "arguments are: "$1

case $1 in
    start)
        echo "Running container start"
        cd $HA
        hass -c ./config --debug
    ;;
    dev-setup)
        get_dev
    ;;
    install)
        echo "Running container post installation"
        script/setup
    ;;
    translations)
        echo "Running container start"
        cd $HA
        python3 -m script.translations develop
    ;;
    hassfest)
        echo "Running container start"
        python3 -m script.hassfest
        # python -m script.hassfest --requirements --action validate --integration-path config/custom_components/versatile_thermostat/
    ;;
    restart)
        echo "Killing existing container"
        pkill hass
        echo "Killing existing container"
        cd $HA
        hass -c ./config
    ;;
esac
