from homeassistant.components.climate.const import (
    PRESET_BOOST,
    PRESET_COMFORT,
    PRESET_ECO,
)
from custom_components.versatile_thermostat.const import (
    CONF_NAME,
    CONF_HEATER,
    CONF_THERMOSTAT_CLIMATE,
    CONF_THERMOSTAT_SWITCH,
    CONF_THERMOSTAT_TYPE,
    CONF_TEMP_SENSOR,
    CONF_EXTERNAL_TEMP_SENSOR,
    CONF_CYCLE_MIN,
    CONF_TEMP_MAX,
    CONF_TEMP_MIN,
    CONF_PROP_FUNCTION,
    PROPORTIONAL_FUNCTION_TPI,
    CONF_TPI_COEF_INT,
    CONF_TPI_COEF_EXT,
    CONF_MINIMAL_ACTIVATION_DELAY,
    CONF_SECURITY_DELAY_MIN,
    CONF_SECURITY_MIN_ON_PERCENT,
    CONF_SECURITY_DEFAULT_ON_PERCENT,
    CONF_USE_WINDOW_FEATURE,
    CONF_USE_MOTION_FEATURE,
    CONF_USE_POWER_FEATURE,
    CONF_USE_PRESENCE_FEATURE,
)

MOCK_TH_OVER_SWITCH_USER_CONFIG = {
    CONF_NAME: "TheOverSwitchMockName",
    CONF_THERMOSTAT_TYPE: CONF_THERMOSTAT_SWITCH,
    CONF_TEMP_SENSOR: "sensor.mock_temp_sensor",
    CONF_EXTERNAL_TEMP_SENSOR: "sensor.mock_ext_temp_sensor",
    CONF_CYCLE_MIN: 5,
    CONF_TEMP_MIN: 15,
    CONF_TEMP_MAX: 30,
    # Keep all additional optional features to false
}

MOCK_TH_OVER_SWITCH_TYPE_CONFIG = {
    CONF_HEATER: "switch.mock_switch",
    CONF_PROP_FUNCTION: PROPORTIONAL_FUNCTION_TPI,
}

MOCK_TH_OVER_SWITCH_TPI_CONFIG = {
    CONF_TPI_COEF_INT: 0.3,
    CONF_TPI_COEF_EXT: 0.1,
}


MOCK_PRESETS_CONFIG = {
    PRESET_ECO + "_temp": 16,
    PRESET_COMFORT + "_temp": 17,
    PRESET_BOOST + "_temp": 18,
}

MOCK_ADVANCED_CONFIG = {
    CONF_MINIMAL_ACTIVATION_DELAY: 10,
    CONF_SECURITY_DELAY_MIN: 5,
    CONF_SECURITY_MIN_ON_PERCENT: 0.4,
    CONF_SECURITY_DEFAULT_ON_PERCENT: 0.3,
}

MOCK_DEFAULT_FEATURE_CONFIG = {
    CONF_USE_WINDOW_FEATURE: False,
    CONF_USE_MOTION_FEATURE: False,
    CONF_USE_POWER_FEATURE: False,
    CONF_USE_PRESENCE_FEATURE: False,
}
